package view.people;

import comboBoxModel.CityComboBoxModel;
import controller.PersonController;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import model.Person;
import tableModel.PersonTableModel;
import util.GenericActionListener;

public class PeopleInternalFrame extends util.GenericInternalFrame<PersonController, Person, PersonTableModel> {

    public PeopleInternalFrame(PersonController controller) {
        initComponents();

        this.controller = controller;

        this.listTableModel = new PersonTableModel(controller.getKind());

        this.tablePeople.setModel(listTableModel);

        this.listener = new GenericActionListener(this, tablePeople, listTableModel, controller);

        loadResources();
        
        loadPersonResources();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form = new javax.swing.JPanel();
        formAvatar = new javax.swing.JPanel();
        labelAvatar = new javax.swing.JLabel();
        labelLegalName = new javax.swing.JLabel();
        formLegalName = new javax.swing.JTextField();
        labelDocument1 = new javax.swing.JLabel();
        labelDocument2 = new javax.swing.JLabel();
        formSubmit = new javax.swing.JButton();
        formName = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelCellPhone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        formEmail = new javax.swing.JTextField();
        labelCity = new javax.swing.JLabel();
        formCity = new javax.swing.JComboBox();
        formAddress = new javax.swing.JTextField();
        labelAddress = new javax.swing.JLabel();
        addAvatar = new javax.swing.JButton();
        removeAvatar = new javax.swing.JButton();
        labelDistrict = new javax.swing.JLabel();
        formDistrict = new javax.swing.JTextField();
        formPhone = new javax.swing.JFormattedTextField();
        formCellPhone = new javax.swing.JFormattedTextField();
        formDocument1 = new javax.swing.JFormattedTextField();
        formDocument2 = new javax.swing.JFormattedTextField();
        avatarFileChooser = new javax.swing.JFileChooser();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        destroyButton = new javax.swing.JButton();
        search = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        searchName = new javax.swing.JTextField();
        searchSubmit = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        tablePeople = new javax.swing.JTable();

        setClosable(true);
        setTitle("Cadastro de Pessoas");

        form.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        formAvatar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        formAvatar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAvatar.setPreferredSize(new java.awt.Dimension(150, 180));
        formAvatar.add(labelAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 180));

        labelLegalName.setText("Razão Social");

        labelDocument1.setText("CNPJ");

        labelDocument2.setText("IE");

        formSubmit.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        formSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/Save.png"))); // NOI18N
        formSubmit.setText("Gravar");
        formSubmit.setActionCommand("save");

        labelName.setText("Nome Fantasia");

        labelPhone.setText("Telefone");

        labelCellPhone.setText("Celular");

        labelEmail.setText("Email");

        labelCity.setText("Cidade");

        labelAddress.setText("Endereço");

        addAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/plus_16.png"))); // NOI18N
        addAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAvatarActionPerformed(evt);
            }
        });

        removeAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/Delete.png"))); // NOI18N
        removeAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAvatarActionPerformed(evt);
            }
        });

        labelDistrict.setText("Bairro");

        try {
            formPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            formCellPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(formSubmit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formLayout.createSequentialGroup()
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCity)
                            .addComponent(formCity, 0, 154, Short.MAX_VALUE)
                            .addGroup(formLayout.createSequentialGroup()
                                .addComponent(addAvatar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeAvatar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avatarFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelDistrict)
                            .addComponent(formDistrict)
                            .addComponent(formAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(formLegalName)
                            .addGroup(formLayout.createSequentialGroup()
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelDocument1)
                                    .addComponent(labelPhone)
                                    .addComponent(formPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(formDocument1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formCellPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addGroup(formLayout.createSequentialGroup()
                                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDocument2)
                                            .addComponent(labelCellPhone))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(formDocument2)))
                            .addComponent(formName)
                            .addComponent(formEmail)
                            .addGroup(formLayout.createSequentialGroup()
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAddress)
                                    .addComponent(labelLegalName)
                                    .addComponent(labelName)
                                    .addComponent(labelEmail))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formLayout.createSequentialGroup()
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(formLayout.createSequentialGroup()
                                .addComponent(labelLegalName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formLegalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelDocument1)
                                    .addComponent(labelDocument2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(formDocument1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formDocument2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelPhone)
                                    .addComponent(labelCellPhone)))
                            .addComponent(formAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avatarFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addAvatar)
                    .addComponent(removeAvatar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(labelCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddress)
                    .addComponent(labelDistrict))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formSubmit)
                .addContainerGap())
        );

        addButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/plus_16.png"))); // NOI18N
        addButton.setText("Adicionar");
        addButton.setActionCommand("add");

        editButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/edit_16.png"))); // NOI18N
        editButton.setText("Alterar");
        editButton.setActionCommand("edit");

        destroyButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        destroyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/trash_16.png"))); // NOI18N
        destroyButton.setText("Excluír");
        destroyButton.setActionCommand("destroy");

        search.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        jLabel7.setText("Nome");

        searchSubmit.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        searchSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/Find.png"))); // NOI18N
        searchSubmit.setText("Pesquisar");

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchLayout.createSequentialGroup()
                        .addContainerGap(378, Short.MAX_VALUE)
                        .addComponent(searchSubmit)))
                .addContainerGap())
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePeople.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(tablePeople);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destroyButton))
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(destroyButton)
                            .addComponent(editButton)
                            .addComponent(addButton)))
                    .addComponent(form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private Image getScaledImage(Image srcImg, int w, int h){
        BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImg.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(srcImg, 0, 0, w, h, null);
        g2.dispose();
        return resizedImg;
    }
    
    private void addAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAvatarActionPerformed
        int popFile = avatarFileChooser.showOpenDialog(this);
        
        if (popFile == avatarFileChooser.APPROVE_OPTION) {
            File arq = avatarFileChooser.getSelectedFile();
            
            ImageIcon image = new ImageIcon(arq.getPath());
            
            image.setImage( getScaledImage(image.getImage(), labelAvatar.getWidth(), labelAvatar.getHeight()) );
            
            this.object.setAvatar(getImgBytes(image.getImage()));
            
            labelAvatar.setIcon( image );
        }
    }//GEN-LAST:event_addAvatarActionPerformed

    private BufferedImage getBufferedImage(Image image) {
        int width = image.getWidth(null);
        int height = image.getHeight(null);
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        return bi;
    }    
    
    private byte [] getImgBytes(Image image) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            ImageIO.write(getBufferedImage(image), "JPEG", baos);
        } catch (IOException ex) {
        }
        return baos.toByteArray();
    }    
    
    private void removeAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAvatarActionPerformed
        labelAvatar.setIcon(null);
        this.object.setAvatar(null);
    }//GEN-LAST:event_removeAvatarActionPerformed

    private void loadPersonResources() {
        if ("supplier".equals(controller.getKind())) {
            try {
                this.formDocument1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
                this.formDocument2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
            } catch (java.text.ParseException ex) { 
            }       
            
            this.labelLegalName.setText("Razão Social");
            this.labelName.setText("Nome Fantasia");
            this.labelDocument1.setText("CNPJ");
            this.labelDocument2.setText("IE");            
        } else {
            try {
                this.formDocument1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
                this.formDocument2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-#")));
            } catch (java.text.ParseException ex) { 
            }            

            this.labelLegalName.setText("Nome");
            this.labelName.setText("Apelido");
            this.labelDocument1.setText("CPF");
            this.labelDocument2.setText("RG");        
        }
        
        switch (controller.getKind()) {
            case "employee":
                this.setTitle("Cadastro de Colaboradores");
                this.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/employees_16.png")));

                break;
            case "supplier":
                this.setTitle("Cadastro de Fornecedores");
                this.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/suppliers_16.png")));
                
                break;
            default:
                this.setTitle("Cadastro de Clientes");
                this.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/customers_16.png")));
        }
        
        formCity.setModel(new CityComboBoxModel());
    }
    
    @Override
    public JButton getAddButton() {
        return addButton;
    }

    @Override
    public JButton getDestroyButton() {
        return destroyButton;
    }

    @Override
    public JButton getEditButton() {
        return editButton;
    }

    @Override
    public JButton getFormSubmit() {
        return formSubmit;
    }

    @Override
    protected void enableOrDisableFields(boolean enable) {
        this.formLegalName.setEnabled(enable);
        this.formName.setEnabled(enable);
        this.formDocument1.setEnabled(enable);
        this.formDocument2.setEnabled(enable);
        this.formPhone.setEnabled(enable);
        this.formCellPhone.setEnabled(enable);
        this.formEmail.setEnabled(enable);
        this.formCity.setEnabled(enable);
        this.formDistrict.setEnabled(enable);
        this.formAddress.setEnabled(enable);
        
        this.formSubmit.setEnabled(enable);

        this.form.repaint();
    }

    @Override
    protected void setNewObject() {
        this.object = new Person();
        this.object.setKind(controller.getKind());
    }

    @Override
    protected void mappingObjectToForm() {
        this.formLegalName.setText(object.getLegalName());
        this.formName.setText(object.getName());
        this.formDocument1.setText(object.getDocument1());
        this.formDocument2.setText(object.getDocument2());
        this.formPhone.setText(object.getPhone());
        this.formCellPhone.setText(object.getCellPhone());
        this.formEmail.setText(object.getEmail());
        this.formCity.getModel().setSelectedItem(object.getCity());
        this.formDistrict.setText(object.getDistrict());
        this.formAddress.setText(object.getAddress());
        
        if (object.getAvatar() != null) {
            try {
                BufferedImage img = ImageIO.read(new ByteArrayInputStream(object.getAvatar()));
                
                this.labelAvatar.setIcon(new ImageIcon(img));
            } catch (IOException ex) {
                Logger.getLogger(PeopleInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.labelAvatar.setIcon(null);
        }
        
    }

    @Override
    protected void mappingFormToObject() {
        this.object.setLegalName(formLegalName.getText());
        this.object.setName(formName.getText());
        this.object.setDocument1(formDocument1.getText());
        this.object.setDocument2(formDocument2.getText());
        this.object.setPhone(formPhone.getText());
        this.object.setCellPhone(formCellPhone.getText());
        this.object.setEmail(formEmail.getText());
        this.object.setCity((model.City) formCity.getModel().getSelectedItem());
        this.object.setDistrict(formDistrict.getText());
        this.object.setAddress(formAddress.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAvatar;
    private javax.swing.JButton addButton;
    private javax.swing.JFileChooser avatarFileChooser;
    private javax.swing.JButton destroyButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel form;
    private javax.swing.JTextField formAddress;
    private javax.swing.JPanel formAvatar;
    private javax.swing.JFormattedTextField formCellPhone;
    private javax.swing.JComboBox formCity;
    private javax.swing.JTextField formDistrict;
    private javax.swing.JFormattedTextField formDocument1;
    private javax.swing.JFormattedTextField formDocument2;
    private javax.swing.JTextField formEmail;
    private javax.swing.JTextField formLegalName;
    private javax.swing.JTextField formName;
    private javax.swing.JFormattedTextField formPhone;
    private javax.swing.JButton formSubmit;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelAvatar;
    private javax.swing.JLabel labelCellPhone;
    private javax.swing.JLabel labelCity;
    private javax.swing.JLabel labelDistrict;
    private javax.swing.JLabel labelDocument1;
    private javax.swing.JLabel labelDocument2;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLegalName;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JButton removeAvatar;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel search;
    private javax.swing.JTextField searchName;
    private javax.swing.JButton searchSubmit;
    private javax.swing.JTable tablePeople;
    // End of variables declaration//GEN-END:variables
}
