package view.person;

import view.components.table.TablePanel;
import view.components.toolbar.BaseToolBar;

public class PersonInternalFrame extends javax.swing.JInternalFrame {

    private PersonActionListener listener;
    private String kind;
    
    public PersonInternalFrame(String kind) {
        this.kind = kind;
        
        listener = new PersonActionListener(this, kind);
        
        switch (kind) {
            case "customer":
                setTitle("Clientes");
                setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/customers_16.png")));
                break;
            case "supplier":
                setTitle("Fornecedores");
                setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/suppliers_16.png")));
                break;
            case "employee":
                setTitle("Funcionários");
                setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/employees_16.png")));
                break;
        }
        
        initComponents();   
        
        listener.initComponents();
    }

    public FormPanel getFormPanel() {
        return formPanel;
    }

    public TablePanel getListPanel() {
        return tablePanel;
    }
    
    public String getPersonKind() {
        return kind;
    }

    public BaseToolBar getBaseToolBar() {
        return baseToolBar;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelContent = new javax.swing.JPanel();
        baseToolBar = new view.components.toolbar.BaseToolBar(listener);
        formPanel = new view.person.FormPanel();
        tablePanel = new view.components.table.TablePanel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1000, 585));

        panelContent.setLayout(new java.awt.GridBagLayout());

        baseToolBar.setMinimumSize(new java.awt.Dimension(1000, 40));
        baseToolBar.setPreferredSize(new java.awt.Dimension(1000, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        panelContent.add(baseToolBar, gridBagConstraints);

        formPanel.setMinimumSize(new java.awt.Dimension(450, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 5);
        panelContent.add(formPanel, gridBagConstraints);

        tablePanel.setMinimumSize(new java.awt.Dimension(520, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        panelContent.add(tablePanel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.components.toolbar.BaseToolBar baseToolBar;
    private view.person.FormPanel formPanel;
    private javax.swing.JPanel panelContent;
    private view.components.table.TablePanel tablePanel;
    // End of variables declaration//GEN-END:variables
}
