package view.person;

import view.components.header.BaseHeader;

public class PersonInternalFrame extends javax.swing.JInternalFrame {

    private PersonActionListener listener;
    private String person_kind;
    
    public PersonInternalFrame(String kind) {
        this.person_kind = kind;
        
        listener = new PersonActionListener(this, kind);
        
        switch (kind) {
            case "customer":
                setTitle("Clientes");
                break;
            case "supplier":
                setTitle("Fornecedores");
                break;
            case "employee":
                setTitle("Funcionários");
                break;
        }
        
        initComponents();   
        
        listener.initComponents();
    }

    public FormPanel getFormPanel() {
        return formPanel;
    }

    public ListPanel getListPanel() {
        return listPanel;
    }
    
    public String getPersonKind() {
        return person_kind;
    }

    public BaseHeader getBaseHeader() {
        return baseHeader;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        formPanel = new view.person.FormPanel( getPersonKind() );
        listPanel = new view.person.ListPanel();
        baseHeader = new view.components.header.BaseHeader(getTitle(), listener);

        setClosable(true);

        javax.swing.GroupLayout baseHeaderLayout = new javax.swing.GroupLayout(baseHeader);
        baseHeader.setLayout(baseHeaderLayout);
        baseHeaderLayout.setHorizontalGroup(
            baseHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        baseHeaderLayout.setVerticalGroup(
            baseHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addComponent(baseHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.components.header.BaseHeader baseHeader;
    private view.person.FormPanel formPanel;
    private view.person.ListPanel listPanel;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
