package view.genre;

import view.components.toolbar.BaseToolBar;

public class GenreInternalFrame extends javax.swing.JInternalFrame {

    private GenreActionListener listener;
    
    public GenreInternalFrame() {
        listener = new GenreActionListener(this);
        
        initComponents();
        
        listener.initComponents();
    }

    public BaseToolBar getBaseToolBar() {
        return baseToolBar;
    }

    public FormPanel getFormPanel() {
        return formPanel;
    }

    public ListPanel getListPanel() {
        return listPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelContent = new javax.swing.JPanel();
        baseToolBar = new view.components.toolbar.BaseToolBar(listener);
        formPanel = new view.genre.FormPanel();
        listPanel = new view.genre.ListPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Generos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/category_16.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 585));

        panelContent.setLayout(new java.awt.GridBagLayout());

        baseToolBar.setMinimumSize(new java.awt.Dimension(1000, 40));
        baseToolBar.setPreferredSize(new java.awt.Dimension(1000, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        panelContent.add(baseToolBar, gridBagConstraints);

        formPanel.setMinimumSize(new java.awt.Dimension(450, 500));
        formPanel.setPreferredSize(new java.awt.Dimension(450, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 5);
        panelContent.add(formPanel, gridBagConstraints);

        listPanel.setMinimumSize(new java.awt.Dimension(520, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        panelContent.add(listPanel, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelContent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelContent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.components.toolbar.BaseToolBar baseToolBar;
    private view.genre.FormPanel formPanel;
    private view.genre.ListPanel listPanel;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
