package view.movies;

import java.awt.Frame;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.GenreComboBoxModel;
import view.actors.ListPanel;

public final class FormPanel extends javax.swing.JPanel {

    private Frame parent;
    
    public FormPanel() {
        initComponents();
        
        selectGenre.setModel(new GenreComboBoxModel());
        
        enableOrDisableFields(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        inputTitle = new javax.swing.JTextField();
        labelGenre = new javax.swing.JLabel();
        selectGenre = new javax.swing.JComboBox();
        labelReleaseIn = new javax.swing.JLabel();
        tabPanel = new javax.swing.JTabbedPane();
        panelMedias = new javax.swing.JPanel();
        mediasListPanel = new view.medias.ListPanel();
        panelActors = new javax.swing.JPanel();
        actorsListPanel = new view.actors.ListPanel();
        panelSynopsis = new javax.swing.JPanel();
        synopsisScrollPane = new javax.swing.JScrollPane();
        textAreaSynopsis = new javax.swing.JTextArea();
        inputReleaseIn = new javax.swing.JFormattedTextField();
        labelId = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(450, 500));
        setPreferredSize(new java.awt.Dimension(450, 500));

        labelTitle.setText("Título");

        labelGenre.setText("Genero");

        labelReleaseIn.setText("Lançado em");

        javax.swing.GroupLayout panelMediasLayout = new javax.swing.GroupLayout(panelMedias);
        panelMedias.setLayout(panelMediasLayout);
        panelMediasLayout.setHorizontalGroup(
            panelMediasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mediasListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );
        panelMediasLayout.setVerticalGroup(
            panelMediasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediasLayout.createSequentialGroup()
                .addComponent(mediasListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
        );

        tabPanel.addTab("Mídias", panelMedias);

        javax.swing.GroupLayout panelActorsLayout = new javax.swing.GroupLayout(panelActors);
        panelActors.setLayout(panelActorsLayout);
        panelActorsLayout.setHorizontalGroup(
            panelActorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actorsListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );
        panelActorsLayout.setVerticalGroup(
            panelActorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActorsLayout.createSequentialGroup()
                .addComponent(actorsListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
        );

        tabPanel.addTab("Atores", panelActors);

        textAreaSynopsis.setColumns(20);
        textAreaSynopsis.setRows(5);
        synopsisScrollPane.setViewportView(textAreaSynopsis);

        javax.swing.GroupLayout panelSynopsisLayout = new javax.swing.GroupLayout(panelSynopsis);
        panelSynopsis.setLayout(panelSynopsisLayout);
        panelSynopsisLayout.setHorizontalGroup(
            panelSynopsisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSynopsisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(synopsisScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSynopsisLayout.setVerticalGroup(
            panelSynopsisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSynopsisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(synopsisScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.addTab("Sinopse", panelSynopsis);

        try {
            inputReleaseIn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelGenre)
                                .addGap(174, 174, 174)
                                .addComponent(labelReleaseIn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(selectGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputReleaseIn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGenre)
                            .addComponent(labelReleaseIn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputReleaseIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selectGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void enableOrDisableFields(boolean enable) {
         inputReleaseIn.enable(enable);
         inputTitle.enable(enable);
         selectGenre.enable(enable);
         textAreaSynopsis.enable(enable);
         
         this.repaint();
    }

    public ListPanel getActorsListPanel() {
        return actorsListPanel;
    }

    public void setActorsListPanel(ListPanel actorsListPanel) {
        this.actorsListPanel = actorsListPanel;
    }

    public JFormattedTextField getInputReleaseIn() {
        return inputReleaseIn;
    }

    public void setInputReleaseIn(JFormattedTextField inputReleaseIn) {
        this.inputReleaseIn = inputReleaseIn;
    }

    public JTextField getInputTitle() {
        return inputTitle;
    }

    public void setInputTitle(JTextField inputTitle) {
        this.inputTitle = inputTitle;
    }

    public view.medias.ListPanel getMediasListPanel() {
        return mediasListPanel;
    }

    public void setMediasListPanel(view.medias.ListPanel mediasListPanel) {
        this.mediasListPanel = mediasListPanel;
    }

    public JComboBox getSelectGenre() {
        return selectGenre;
    }

    public void setSelectGenre(JComboBox selectGenre) {
        this.selectGenre = selectGenre;
    }

    public JTextArea getTextAreaSynopsis() {
        return textAreaSynopsis;
    }

    public void setTextAreaSynopsis(JTextArea textAreaSynopsis) {
        this.textAreaSynopsis = textAreaSynopsis;
    }

    public JLabel getLabelId() {
        return labelId;
    }

    public void setLabelId(JLabel labelId) {
        this.labelId = labelId;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.actors.ListPanel actorsListPanel;
    private javax.swing.JFormattedTextField inputReleaseIn;
    private javax.swing.JTextField inputTitle;
    private javax.swing.JLabel labelGenre;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelReleaseIn;
    private javax.swing.JLabel labelTitle;
    private view.medias.ListPanel mediasListPanel;
    private javax.swing.JPanel panelActors;
    private javax.swing.JPanel panelMedias;
    private javax.swing.JPanel panelSynopsis;
    private javax.swing.JComboBox selectGenre;
    private javax.swing.JScrollPane synopsisScrollPane;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTextArea textAreaSynopsis;
    // End of variables declaration//GEN-END:variables

}
