package view.main;

import com.jgoodies.looks.plastic.PlasticXPLookAndFeel;
import com.jgoodies.looks.plastic.theme.SkyBlue;
import view.actor.ActorInternalFrame;
import view.genre.GenreInternalFrame;
import view.person.PersonInternalFrame;
import view.report.LocationsByPeriodInternalFrame;
import view.user.UserInternalFrame;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        entriesMenu = new javax.swing.JMenu();
        customersMenuItem = new javax.swing.JMenuItem();
        suppliersMenuItem = new javax.swing.JMenuItem();
        employeesMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        moviesMenuItem = new javax.swing.JMenuItem();
        genresMenuItem = new javax.swing.JMenuItem();
        actorsMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        usersMenuItem = new javax.swing.JMenuItem();
        optionsMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        movieMenu = new javax.swing.JMenu();
        reservationMenuItem = new javax.swing.JMenuItem();
        locationMenuItem = new javax.swing.JMenuItem();
        devolutionMenuItem = new javax.swing.JMenuItem();
        reportMenu = new javax.swing.JMenu();
        locationsByPeriodMenuItem = new javax.swing.JMenuItem();
        inventoryOfMoviesMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Video Locadoras");
        setPreferredSize(getMaximumSize());

        entriesMenu.setMnemonic('f');
        entriesMenu.setText("Cadastros");

        customersMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/customers_16.png"))); // NOI18N
        customersMenuItem.setMnemonic('o');
        customersMenuItem.setText("Clientes");
        customersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersMenuItemActionPerformed(evt);
            }
        });
        entriesMenu.add(customersMenuItem);

        suppliersMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/suppliers_16.png"))); // NOI18N
        suppliersMenuItem.setMnemonic('s');
        suppliersMenuItem.setText("Fornecedores");
        suppliersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersMenuItemActionPerformed(evt);
            }
        });
        entriesMenu.add(suppliersMenuItem);

        employeesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/employees_16.png"))); // NOI18N
        employeesMenuItem.setMnemonic('a');
        employeesMenuItem.setText("Colaboradores");
        employeesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesMenuItemActionPerformed(evt);
            }
        });
        entriesMenu.add(employeesMenuItem);
        entriesMenu.add(jSeparator1);

        moviesMenuItem.setText("Filmes");
        entriesMenu.add(moviesMenuItem);

        genresMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/category_16.png"))); // NOI18N
        genresMenuItem.setMnemonic('t');
        genresMenuItem.setText("Generos");
        genresMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genresMenuItemActionPerformed(evt);
            }
        });
        entriesMenu.add(genresMenuItem);

        actorsMenuItem.setText("Atores");
        actorsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actorsMenuItemActionPerformed(evt);
            }
        });
        entriesMenu.add(actorsMenuItem);
        entriesMenu.add(jSeparator2);

        usersMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/user_16.png"))); // NOI18N
        usersMenuItem.setText("Usuários");
        usersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersMenuItemActionPerformed(evt);
            }
        });
        entriesMenu.add(usersMenuItem);

        optionsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/config_16.png"))); // NOI18N
        optionsMenuItem.setText("Opções do Sistema");
        entriesMenu.add(optionsMenuItem);
        entriesMenu.add(jSeparator3);

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/sign_out_16.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Sair");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        entriesMenu.add(exitMenuItem);

        menuBar.add(entriesMenu);

        movieMenu.setMnemonic('e');
        movieMenu.setText("Filmes");

        reservationMenuItem.setText("Reserva");
        movieMenu.add(reservationMenuItem);

        locationMenuItem.setText("Locação");
        movieMenu.add(locationMenuItem);

        devolutionMenuItem.setText("Devolução");
        movieMenu.add(devolutionMenuItem);

        menuBar.add(movieMenu);

        reportMenu.setText("Relatórios");

        locationsByPeriodMenuItem.setText("Locações Por Período");
        locationsByPeriodMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationsByPeriodMenuItemActionPerformed(evt);
            }
        });
        reportMenu.add(locationsByPeriodMenuItem);

        inventoryOfMoviesMenuItem.setText("Inventário de Filmes");
        reportMenu.add(inventoryOfMoviesMenuItem);

        menuBar.add(reportMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ajuda");

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/about_16.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Sobre");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void customersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersMenuItemActionPerformed
        PersonInternalFrame personIF = new PersonInternalFrame("customer");
        
        personIF.setLocation((getWidth() - personIF.getWidth()) / 2, 40);
        
        personIF.setVisible(true);
        
        desktopPane.add(personIF);
    }//GEN-LAST:event_customersMenuItemActionPerformed

    private void suppliersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersMenuItemActionPerformed
        PersonInternalFrame personIF = new PersonInternalFrame("supplier");
        
        personIF.setLocation((getWidth() - personIF.getWidth()) / 2, 40);
        
        personIF.setVisible(true);
        
        desktopPane.add(personIF);
    }//GEN-LAST:event_suppliersMenuItemActionPerformed
    
    private void employeesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesMenuItemActionPerformed
        PersonInternalFrame personIF = new PersonInternalFrame("employee");
        
        personIF.setLocation((getWidth() - personIF.getWidth()) / 2, 40);
        
        personIF.setVisible(true);
        
        desktopPane.add(personIF);
    }//GEN-LAST:event_employeesMenuItemActionPerformed

    private void usersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersMenuItemActionPerformed
        UserInternalFrame userIF = new UserInternalFrame();
        
        userIF.setLocation((getWidth() - userIF.getWidth()) / 2, 40);
        
        userIF.setVisible(true);
        
        desktopPane.add(userIF);
    }//GEN-LAST:event_usersMenuItemActionPerformed

    private void genresMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genresMenuItemActionPerformed
        GenreInternalFrame genreIF = new GenreInternalFrame();
        
        genreIF.setLocation((getWidth() - genreIF.getWidth()) / 2, 40);
        
        genreIF.setVisible(true);
        
        desktopPane.add(genreIF);
    }//GEN-LAST:event_genresMenuItemActionPerformed

    private void actorsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actorsMenuItemActionPerformed
        ActorInternalFrame actorIF = new ActorInternalFrame();
        
        actorIF.setLocation((getWidth() - actorIF.getWidth()) / 2, 40);
        
        actorIF.setVisible(true);
        
        desktopPane.add(actorIF);
    }//GEN-LAST:event_actorsMenuItemActionPerformed

    private void locationsByPeriodMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationsByPeriodMenuItemActionPerformed
        LocationsByPeriodInternalFrame frame = new LocationsByPeriodInternalFrame();
        
        frame.setLocation((getWidth() - frame.getWidth()) / 2, 40);
        
        frame.setVisible(true);
        
        desktopPane.add(frame);
    }//GEN-LAST:event_locationsByPeriodMenuItemActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        PlasticXPLookAndFeel.setPlasticTheme(new SkyBlue());
        
        try {
            javax.swing.UIManager.setLookAndFeel( new PlasticXPLookAndFeel() );
        } catch (javax.swing.UnsupportedLookAndFeelException ex) { // ClassNotFoundException | InstantiationException | IllegalAccessException | 
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem actorsMenuItem;
    private javax.swing.JMenuItem customersMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem devolutionMenuItem;
    private javax.swing.JMenuItem employeesMenuItem;
    private javax.swing.JMenu entriesMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem genresMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem inventoryOfMoviesMenuItem;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem locationMenuItem;
    private javax.swing.JMenuItem locationsByPeriodMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu movieMenu;
    private javax.swing.JMenuItem moviesMenuItem;
    private javax.swing.JMenuItem optionsMenuItem;
    private javax.swing.JMenu reportMenu;
    private javax.swing.JMenuItem reservationMenuItem;
    private javax.swing.JMenuItem suppliersMenuItem;
    private javax.swing.JMenuItem usersMenuItem;
    // End of variables declaration//GEN-END:variables
}
